Auction/Models/Lot.cs
namespace Auction.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Lot")]
    public partial class Lot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Lot()
        {
            Bet = new HashSet<Bet>();
            Comment = new HashSet<Comment>();
        }

        public Guid LotID { get; set; }

        [Required]
        [StringLength(128)]
        public string Title { get; set; }

        public DateTime StartTime { get; set; }

        [Required]
        public DateTime EndTime { get; set; }

        [Required]
        public double StartPrice { get; set; }

        public double NowPrice { get; set; }

        public double? BuyNowPrice { get; set; }

        [Required]
        public long Step { get; set; }

        [StringLength(128)]
        public string Picture { get; set; }

        public Guid UserID { get; set; }

        public Guid? CategoryID { get; set; }

        public Guid StatusID { get; set; }

        public Guid? WinnerID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bet> Bet { get; set; }

        public virtual Category Category { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }

        public virtual Status Status { get; set; }

        public virtual User User { get; set; }

        public virtual User Winner { get; set; }
    }
}

Auction/Controllers/BetController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Auction.Models;

namespace Auction.Controllers
{
    public class BetController : Controller
    {
        private AuctionContext db = new AuctionContext();

        // GET: Bet/Create
        public ActionResult Create(Guid lotID, double betPrice)
        {
            Bet bet = new Bet();
            bet.BetPrice = betPrice;
            bet.LotID = lotID;
            return PartialView(bet);
        }

        // POST: Bet/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Bet bet)
        {
            if (ModelState.IsValid)
            {
                User user = db.User.FirstOrDefault(u => u.Login == User.Identity.Name);
                if (user == null)
                {
                    ModelState.AddModelError("", "Войдите чтобы создать комментарий");
                }
                else
                {
                    Lot lot = db.Lot.Find(bet.LotID);
                    if (bet.BetPrice >= lot.NowPrice + lot.Step)
                    {
                        bet.BetID = Guid.NewGuid();
                        bet.BetTime = DateTime.Now;
                        bet.UserID = user.UserID;
                        db.Bet.Add(bet);

                        if (lot.BuyNowPrice != null && bet.BetPrice >= lot.BuyNowPrice)
                        {
                            lot.WinnerID = bet.UserID;
                            lot.StatusID = db.Status.FirstOrDefault(s => s.Name == "Закрыт").StatusID;
                        }
                        lot.NowPrice = bet.BetPrice;
                        db.Entry(lot).State = EntityState.Modified;

                        db.SaveChanges();
                        //return RedirectToAction("Create", new { lotID = bet.LotID, betPrice = bet.BetPrice + lot.Step});
                        return RedirectToAction("Details", "Lots", new { id = bet.LotID});
                    } else
                    {
                        ModelState.AddModelError("", "Неверная цена");
                    }
                }
            }
            return PartialView(bet);
        }
    }
}

Auction/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Auction.Models;

namespace Auction.Controllers
{
    public class CommentController : Controller
    {
        private AuctionContext db = new AuctionContext();
        // GET: Comment
        public ActionResult Comments(Guid id)
        {
            var comments = db.Comment.Include(l => l.User).Where(l => l.LotID == id).OrderByDescending(c => c.CommentTime);
            return PartialView(comments.ToList());
        }

        // GET: Comment/Create
        public ActionResult Create(Guid id)
        {
            Comment comment = new Comment();
            comment.LotID = id;
            return PartialView(comment);
        }

        // POST: Comment/Create
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Comment comment)
        {
            if (ModelState.IsValid)
            {
                User user = db.User.FirstOrDefault(u => u.Login == User.Identity.Name);
                if (user == null)
                {
                    ModelState.AddModelError("", "Войдите чтобы создать комментарий");
                }
                else
                {
                    comment.CommentID = Guid.NewGuid();
                    comment.CommentTime = DateTime.Now;
                    comment.UserID = user.UserID;
                    db.Comment.Add(comment);
                    db.SaveChanges();
                    return RedirectToAction("Create", new { id = comment.LotID });
                }
            }
            return PartialView();
        }

        // POST: Comment/Delete/5
        [HttpPost]
        public ActionResult Delete(Guid id)
        {
            Comment comment = db.Comment.Find(id);
            var lotID = comment.LotID;
            db.Comment.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Create", new { id = lotID });
        }
    }
}

Auction/Controllers/LotsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Auction.Models;

namespace Auction.Controllers
{
    public class LotsController : Controller
    {
        private AuctionContext db = new AuctionContext();

        // GET: Lots
        public ActionResult Index()
        {
            var lot = db.Lot.Include(l => l.Category).Include(l => l.Status).Include(l => l.User).Include(l => l.Winner);
            return View(lot.ToList());
        }

        // GET: Lots Find
        public ActionResult LotsFind(string key = "", Guid? id = null)
        {   
            var lot = db.Lot.Include(l => l.Category).Include(l => l.Status).Include(l => l.User).Include(l => l.Winner);
            switch (key)
            {
                case "category":
                    lot = lot.Where(l => l.CategoryID == id).Where(s => s.Status.Name == "Открыт");
                    break;
                case "user":
                    lot = lot.Where(l => l.User.Login == User.Identity.Name);
                    break;
                case "winner":
                    lot = lot.Where(l => l.Winner.Login == User.Identity.Name);
                    break;
                default:
                    lot = lot.Where(s => s.Status.Name == "Открыт");
                    break;
            }
            if (lot.Any()) return PartialView("Lots", lot.ToList());
            else return Content("<h4>Ничего не найдено</h4>");
        }
        [HttpPost]
        public ActionResult LotsSearch(string name)
        {
            System.Diagnostics.Debug.WriteLine(name);
            var lot = db.Lot.Include(l => l.Category).Include(l => l.Status).Include(l => l.User).Include(l => l.Winner).Where(l => l.Title.Contains(name)).Where(s => s.Status.Name == "Открыт"); ;
            return PartialView("Lots", lot.ToList());
        }

        // GET: Lots/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lot lot = db.Lot.Find(id);
            if (lot == null)
            {
                return HttpNotFound();
            }
            var bets = db.Bet.Where(b => b.LotID == id);
            if (bets == null) ViewBag.Bets = 0;
            else ViewBag.Bets = bets.Count();
            return View(lot);
        }
        
        // GET: Lots/Create
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize]
        public ActionResult ShowCategory(Guid? id, string method, Guid? lotID = null )
        {
            var category = db.Category.Where(c => c.ParentCategoryID == id);
            ViewBag.ParentCategoryID = (id!=null) ? db.Category.Find(id).ParentCategoryID : null;
            ViewBag.method = method;
            if (category.Any())
            {
                ViewBag.lotID = lotID;
                return PartialView("ShowCategory", category.ToList());
            }
            else
            {
                if (method == "create") return RedirectToAction("CreateLot", new { id = id });
                else return RedirectToAction("EditLot", new { lotID = lotID, catID = id });
            }
        }

        // GET: Lots/CreateLot
        [Authorize]
        [HttpGet]
        public ActionResult CreateLot(Guid? id)
        {
            Lot lot = new Lot();
            lot.CategoryID = id;
            lot.StatusID = db.Status.FirstOrDefault(s => s.Name == "Открыт").StatusID;
            var category = db.Category.Find(id);
            ViewBag.Category = category.Name;
            ViewBag.ParentCategoryID = category.ParentCategoryID;
            ViewBag.TimeMin = DateTime.Now.AddDays(1).ToString("s");
            ViewBag.TimeMax = DateTime.Now.AddDays(7).ToString("s");
            return View(lot);
        }

        

        // POST: Lots/CreateLot
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Lot lot, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                User user = db.User.FirstOrDefault(u => u.Login == User.Identity.Name);
                if (user == null)
                {
                    ModelState.AddModelError("", "Войдите чтобы создать лот");
                } 
                else
                {
                    lot.LotID = Guid.NewGuid();
                    if (upload != null)
                    {
                        string path = @"\Pictures\" + lot.LotID + @"\";
                        if (!Directory.Exists(Server.MapPath(path))) Directory.CreateDirectory(Server.MapPath(path));
                        path += "img" + Path.GetExtension(upload.FileName);
                        upload.SaveAs(Server.MapPath(path));
                        lot.Picture = path;
                    } else
                    {
                        lot.Picture = @"\Pictures\noimage.png";
                    }
                    lot.StartTime = DateTime.Now;
                    lot.UserID = user.UserID;
                    lot.NowPrice = lot.StartPrice;
                    db.Lot.Add(lot);
                    db.SaveChanges();
                    return RedirectToAction("Index", "Account");
                }                
            }

            var category = db.Category.Find(lot.CategoryID);
            ViewBag.Category = category.Name;
            ViewBag.ParentCategoryID = category.ParentCategoryID;
            ViewBag.TimeMin = DateTime.Now.AddDays(1).ToString("s");
            ViewBag.TimeMax = DateTime.Now.AddDays(7).ToString("s");
            return View(lot);
        }

        // GET: Lots/Edit/5
        [HttpGet]
        public ActionResult Edit(Guid? id)
        {
            ViewBag.LotID = id;
            return View();
        }
        [HttpGet]
        public ActionResult EditLot(Guid? lotID, Guid? catID = null)
        {
            if (lotID == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lot lot = db.Lot.Find(lotID);
            if (lot == null)
            {
                return HttpNotFound();
            }
            if (catID != null) lot.CategoryID = catID;
            var category = db.Category.Find(lot.CategoryID);
            ViewBag.Category = category.Name;
            ViewBag.ParentCategoryID = category.ParentCategoryID;
            ViewBag.TimeMin = lot.StartTime.AddDays(1).ToString("s");
            ViewBag.TimeMax = lot.StartTime.AddDays(7).ToString("s");
            ViewBag.TimeNow = lot.EndTime.ToString("s");
            ViewBag.Status = new SelectList(db.Status, "StatusID", "Name");
            if (Request.IsAjaxRequest()) return View(lot);
            return PartialView(lot);
        }

        // POST: Lots/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Lot lot, HttpPostedFileBase upload)
        {
            if (ModelState.IsValid)
            {
                if (upload != null)
                {
                    string path = @"\Pictures\" + lot.LotID + @"\";
                    if (!Directory.Exists(Server.MapPath(path))) Directory.CreateDirectory(Server.MapPath(path));
                    path += "img" + Path.GetExtension(upload.FileName);
                    upload.SaveAs(Server.MapPath(path));
                    lot.Picture = path;
                }
                lot.NowPrice = lot.StartPrice;
                db.Entry(lot).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", "Account");
            }
            var category = db.Category.Find(lot.CategoryID);
            ViewBag.Category = category.Name;
            ViewBag.ParentCategoryID = category.ParentCategoryID;
            ViewBag.TimeMin = DateTime.Now.AddDays(1).ToString("s");
            ViewBag.TimeMax = DateTime.Now.AddDays(7).ToString("s");
            ViewBag.Status = new SelectList(db.Status, "StatusID", "Name");
            return View(lot);
        }

        // GET: Lots/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Lot lot = db.Lot.Find(id);
            if (lot == null)
            {
                return HttpNotFound();
            }
            return PartialView(lot);
        }

        // POST: Lots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Lot lot = db.Lot.Find(id);
            db.Lot.Remove(lot);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Auction/Views/Lots/Create.cshtml
@model Auction.Models.Lot

@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<div class="lot-form shadows">
    <div id="lot-create">
        @Html.Action("ShowCategory", new { id = (Guid?)null, method = "create" })
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/ShowPicOnLoad.js")
}

Auction/Views/Lots/CreateLot.cshtml
@model Auction.Models.Lot


@using (Html.BeginForm("Create", "Lots", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4><b>Создать лот</b></h4>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-groups">
            <label class="control-label" for="CategoryID">Категория: </label>
            @Ajax.ActionLink((string)ViewBag.Category, "ShowCategory", new { id = ViewBag.ParentCategoryID, method = "create" }, new AjaxOptions { UpdateTargetId = "lot-create" })
            @Html.HiddenFor(model => model.CategoryID)
        </div>
        <div class="form-groups">
            <p><span>Выберите изображение</span></p>
            <label class="control-label" for="upload">
                <img src="https://cdn.onlinewebfonts.com/svg/thumbnails_60_90197.png" alt="Upload" width="30" height="30">
            </label>
            <img id="uploaded-img" src="#" alt="your image" height="95" hidden/>
            <input id="upload" type="file" name="upload" accept=".jpg, .jpeg, .png">
        </div>
        <div class="form-groups">
            <label class="control-label" for="Title">Название *</label>
            @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @required = "required", maxlength = 128 } })
            @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
        </div>

        <div class="form-groups">
            <label class="control-label" for="Title">Время окончания торгов *</label>
            <input class="form-control" id="EndTime" max=@ViewBag.TimeMax min=@ViewBag.TimeMin value=@ViewBag.TimeMin name="EndTime" type="datetime-local" required />
            @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
        </div>

        <div class="form-groups">
            <label class="control-label" for="StartPrice">Начальная цена *</label>

            <div class="input-group">
                @Html.EditorFor(model => model.StartPrice, new { htmlAttributes = new { @class = "form-control", @required = "required", type = "number", min = 1, step = 0.01 } })
                <span class="input-group-addon">руб.</span>
            </div>
            @Html.ValidationMessageFor(model => model.StartPrice, "", new { @class = "text-danger" })
        </div>

        <div class="form-groups">
            <label class="control-label" for="BuyNowPrice">Блиц-цена</label>
            <div class="input-group">
                @Html.EditorFor(model => model.BuyNowPrice, new { htmlAttributes = new { @class = "form-control", type = "number", step = 0.01 } })
                <span class="input-group-addon">руб.</span>
            </div>
            @Html.ValidationMessageFor(model => model.BuyNowPrice, "", new { @class = "text-danger" })
        </div>

        <div class="form-groups">
            <label class="control-label" for="Step">Шаг ставки *</label>
            <div class="input-group">
                @Html.EditorFor(model => model.Step, new { htmlAttributes = new { @class = "form-control", @required = "required", type = "number", min = 1, step = 0.01 } })
                <span class="input-group-addon">руб.</span>
            </div>
            @Html.ValidationMessageFor(model => model.Step, "", new { @class = "text-danger" })
        </div>

        <div class="form-groups">
            @Html.HiddenFor(model => model.StatusID)
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="submit" value="Создать" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/ShowPicOnLoad.js")
}

Auction/Views/Lots/Delete.cshtml
@model Auction.Models.Lot

<div class="overlay"></div>
<div class="form-horizontal mymodal text-center">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <h5>Вы уверены что хотите удалить лот?</h5>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-1 col-md-10">
                @Html.ActionLink("Назад", "Details", new { id = Model.LotID })
                <input type="submit" value="Удалить" class="btn btn-danger" />
            </div>
        </div>
    }
</div>

Auction/Views/Lots/Details.cshtml
@model Auction.Models.Lot

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="col-md-12 shadows">
    <img src="@Html.DisplayFor(model => model.Picture)" class="col-md-4"/>
    <div class="col-md-8">
        <h3>@Html.DisplayFor(model => model.Title)</h3>
        <p class="gray">Время окончания: @Html.DisplayFor(model => model.EndTime)</p>
        <div class="borders">
            <span>Ставок: </span>
            <b>@ViewBag.Bets</b>
            <span> | Время начала: </span>
            <b>@Html.DisplayFor(model => model.StartTime)</b>
            <span> | </span>
            @Html.DisplayFor(model => model.User.Login)
            @if (this.User.Identity.IsAuthenticated && (this.User.Identity.Name == Model.User.Login || this.User.IsInRole("admin")))
            {
                <span id="links" class="right gray">
                    @Html.ActionLink("Редактировать", "Edit", new { id = Model.LotID }) |
                    @Ajax.ActionLink("Удалить", "Delete", new { id = Model.LotID }, new AjaxOptions { UpdateTargetId = "modal" })
                </span>
            }
        </div>
        <div class="col-md-2">
            <span>Цена</span>
            <div>
                <b class="price-box">@Html.DisplayFor(model => model.NowPrice) руб.</b>
            </div>
        </div>
        <div class="col-md-10" id="bet">
            @if (this.User.Identity.IsAuthenticated && Model.Status.Name == "Открыт")
            {
                if (this.User.Identity.Name != Model.User.Login)
                {
                    @Html.Action("Create", "Bet", new { lotID = Model.LotID, betPrice = Model.NowPrice + Model.Step })
                }
            }
            else if (Model.Status.Name == "Закрыт")
            {
                <p class="text-info">Лот продан</p>
            }
            else
            {
                <p class="text-danger">Войдите, чтобы сделать ставку</p>
            }
        </div>
        @if (Model.BuyNowPrice != null)
        {
            <div class="col-md-12">
                <span>Купить моментально: @Html.DisplayFor(model => model.BuyNowPrice) руб.</span>
            </div>
        }
        <hr />
    </div>
    
    <hr />
</div>
<div class="col-md-12 shadows">
    <h4 class="col-md-12">Комментарии</h4>
    <div id="comments" class="col-md-12">
        @if (this.User.Identity.IsAuthenticated)
        {
            @Html.Action("Create", "Comment", new { id = Model.LotID })
        } else
        {
            <p class="text-danger">Войдите, чтобы просматривать и оставлять комментарии</p>
        }
    </div>
</div>

Auction/Views/Lots/Edit.cshtml
@model Auction.Models.Lot

@{
    ViewBag.Title = "Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<hr />
<div class="lot-form shadows">
    <div id="lot-create">
        @Html.Action("EditLot", new { lotID = ViewBag.LotID })
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/ShowPicOnLoad.js")
}

Auction/Views/Lots/EditLot.cshtml
@model Auction.Models.Lot


@using (Html.BeginForm("Edit", "Lots", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4><b>Редактировать</b></h4>
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-groups">
        <label class="control-label" for="CategoryID">Категория: </label>
        @Ajax.ActionLink((string)ViewBag.Category, "ShowCategory", new { id = ViewBag.ParentCategoryID, method = "edit", lotID = Model.LotID }, new AjaxOptions { UpdateTargetId = "lot-create" })
        @Html.HiddenFor(model => model.CategoryID)
    </div>
    <div class="form-groups">
        <p><span>Выберите изображение</span></p>
        <label class="control-label" for="upload">
            <img src="https://cdn.onlinewebfonts.com/svg/thumbnails_60_90197.png" alt="Upload" width="30" height="30">
        </label>
        <img id="uploaded-img" src="@Html.DisplayFor(model => model.Picture)" alt="your image" height="95" />
        <input id="upload" type="file" name="upload" accept=".jpg, .jpeg, .png">
    </div>
    <div class="form-groups">
        <label class="control-label" for="Title">Название *</label>
        @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", @required = "required", maxlength = 128 } })
        @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
    </div>

    <div class="form-groups">
        <label class="control-label" for="Title">Время окончания торгов *</label>
        <input class="form-control" id="EndTime" max=@ViewBag.TimeMax min=@ViewBag.TimeMin value=@ViewBag.TimeNow name="EndTime" type="datetime-local" required />
        @Html.ValidationMessageFor(model => model.EndTime, "", new { @class = "text-danger" })
    </div>

    <div class="form-groups">
        <label class="control-label" for="StartPrice">Начальная цена *</label>

        <div class="input-group">
            @Html.EditorFor(model => model.StartPrice, new { htmlAttributes = new { @class = "form-control", @required = "required", type = "number", min = 1, step = 0.01 } })
            <span class="input-group-addon">руб.</span>
        </div>
        @Html.ValidationMessageFor(model => model.StartPrice, "", new { @class = "text-danger" })
    </div>

    <div class="form-groups">
        <label class="control-label" for="BuyNowPrice">Блиц-цена</label>
        <div class="input-group">
            @Html.EditorFor(model => model.BuyNowPrice, new { htmlAttributes = new { @class = "form-control", type = "number", step = 0.01 } })
            <span class="input-group-addon">руб.</span>
        </div>
        @Html.ValidationMessageFor(model => model.BuyNowPrice, "", new { @class = "text-danger" })
    </div>

    <div class="form-groups">
        <label class="control-label" for="Step">Шаг ставки *</label>
        <div class="input-group">
            @Html.EditorFor(model => model.Step, new { htmlAttributes = new { @class = "form-control", @required = "required", type = "number", min = 1, step = 0.01 } })
            <span class="input-group-addon">руб.</span>
        </div>
        @Html.ValidationMessageFor(model => model.Step, "", new { @class = "text-danger" })
    </div>
    @if (this.User.IsInRole("admin"))
    {
    <div class="form-groups">
        <label class="control-label" for="Title">Статус</label>
        @Html.DropDownListFor(model => model.StatusID, ViewBag.Status as SelectList,  new { @class = "form-control"} )
        @Html.ValidationMessageFor(model => model.StatusID, "", new { @class = "text-danger" })
    </div>
    }
    <div class="form-groups">
        @Html.HiddenFor(model => model.StatusID)
        @Html.HiddenFor(model => model.LotID)
        @Html.HiddenFor(model => model.StartTime)
        @Html.HiddenFor(model => model.Picture)
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <input type="submit" value="Сохранить" class="btn btn-primary" />
        </div>
    </div>
</div>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/scripts/ShowPicOnLoad.js")
}

Auction/Views/Lots/Index.cshtml
@model IEnumerable<Auction.Models.Lot>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div id="sidebar" class="col-lg-3 shadows">
    @using (Ajax.BeginForm("LotsSearch", "Lots", new AjaxOptions { UpdateTargetId = "lots" }, new { @class = "col-md-12 search", key = "search" }))
    {
        <input type="text" name="name" placeholder="Искать здесь...">
        <input type="submit" value="Поиск" class="btn btn-primary" />
    }
    <div class="col-md-12">
        <h4>Категории</h4>
    </div>
    @Html.Action("CategoryList", "Category", new { id = (Guid?)null })
</div>
<div class="col-lg-9">
    <h2>
        Лоты
    </h2>
    <div id="lots">
        @Html.Action("LotsFind")
    </div>
</div>

Auction/Views/Lots/Lots.cshtml
@model IEnumerable<Auction.Models.Lot>

@foreach (var item in Model)
{
    <div>
        <a href="/Lots/Details/@item.LotID">
            <div class="content">
                <div class="img">
                    <div class="item__img" style="background-image: url(@item.Picture.Replace('\\','/'));">
                    </div>
                </div>
                <div class="info">
                    <span>@Html.DisplayFor(modelItem => item.Title)</span>
                </div>
                <div class="price main">
                    <b class="price-box">@Html.DisplayFor(modelItem => item.NowPrice) руб.</b>
                </div>
                @if (item.BuyNowPrice != null)
                {
                    <div class="price">
                        <span>Купить моментально: @Html.DisplayFor(modelItem => item.BuyNowPrice) руб.</span>
                    </div>
                }
                <div class="bottom">
                    <span>Дата окончания: @Html.DisplayFor(modelItem => item.EndTime)</span>
                </div>
            </div>
            @if (item.Status.Name == "Закрыт")
            {
                <div class="cover"></div>
            }
        </a>
    </div>
}

Auction/Views/Lots/ShowCategory.cshtml
@model IEnumerable<Auction.Models.Category>
<h4><b>Выберите категорию</b></h4>
<ul class="list-unstyled">
    @foreach (var item in Model)
    {
        <li>
            <p>@Ajax.ActionLink(item.Name, "ShowCategory", new { id = item.CategoryID, method = ViewBag.method, lotID = ViewBag.lotID }, new AjaxOptions { UpdateTargetId = "lot-create" })</p>
        </li>
    }
    @if (Model.First().ParentCategoryID != null)
    {
    <li>
        <p>@Ajax.ActionLink("Назад", "ShowCategory", new { id = ViewBag.ParentCategoryID, method = ViewBag.method, lotID = ViewBag.lotID }, new AjaxOptions { UpdateTargetId = "lot-create" }, new { @class = "gray" })</p>
    </li>
    }
</ul>